erDiagram
    ENTITY1 ||--o{ ENTITY2 : has
    ENTITY1 {
        int id PK
        string attribute1
        date attribute2
    }
    
    ENTITY2 {
        int id PK
        int entity1_id FK
        string attribute1
        boolean attribute2
    }
    
    ENTITY3 ||--|{ ENTITY2 : relates_to
    ENTITY3 {
        int id PK
        string name
        string description
    }
